language: cpp
sudo: required
git:
  depth: 1
notifications:
  email: false

os: linux
dist: xenial
env: CMAKE_BUILDER="Unix Makefiles"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libgl1-mesa-dev
      - libxcb-glx0-dev
      - libglu-dev
      - libxi-dev
      - libxcursor-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxxf86vm-dev

before_install:
  - eval "CC=gcc-8 && CXX=g++-8"

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
